# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e67d925fe4b0f65b13deb69a15d4d7d992e2b5662021870be5da7d66fc1f99cfded1d39db0909acd7fe507d3375ec5e85fa31dea4e232d1861dd9076c60221

test:
  secret_key_base: ea67ebb7e95d9951b7777c37df8beb315aba403f22148a43ec2883f419befff7b8a924b1ce84e4113108a3ba13326ba817344797e028265eb7848afa908d2ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
